In [1]:
!pip install torch torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a  = torch.randn(3, 4, 5)
a, a.type()

(tensor([[[-0.0923, -0.3867,  0.6600, -0.7016,  0.1524],
          [-1.1745,  1.1931,  3.2735, -0.7840, -0.3274],
          [-0.4123, -0.4956, -0.7821,  0.6297,  0.9069],
          [ 1.5456, -1.1505, -1.7415,  0.0583, -0.2349]],
 
         [[ 1.4254,  0.8426,  2.0674, -0.0787,  0.0302],
          [ 0.6637,  0.7011,  0.5747, -0.5440,  2.2594],
          [-0.7206, -0.7622,  0.4074, -0.5992,  0.4801],
          [-1.1846,  0.3843, -2.1438,  0.3401,  0.2505]],
 
         [[-1.0028, -1.1013, -0.2987,  0.2351,  0.3740],
          [ 1.3914,  0.1673, -1.5087, -1.4032, -1.4639],
          [ 0.0989,  0.6817, -0.4690,  0.3190,  0.5891],
          [-0.0998, -2.2015, -0.7370, -1.7585, -1.2367]]]),
 'torch.FloatTensor')

In [3]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
a = a.reshape(6, 10)

In [5]:
a.shape

torch.Size([6, 10])

In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b = [1, 4, 2, 2, 1]
b = torch.IntTensor(b)
b, b.shape, b.type()

(tensor([1, 4, 2, 2, 1], dtype=torch.int32),
 torch.Size([5]),
 'torch.IntTensor')

In [7]:
a.reshape(3, 4, 5) * b

tensor([[[-0.0923, -1.5470,  1.3199, -1.4031,  0.1524],
         [-1.1745,  4.7723,  6.5470, -1.5680, -0.3274],
         [-0.4123, -1.9823, -1.5642,  1.2594,  0.9069],
         [ 1.5456, -4.6020, -3.4831,  0.1165, -0.2349]],

        [[ 1.4254,  3.3703,  4.1349, -0.1574,  0.0302],
         [ 0.6637,  2.8045,  1.1493, -1.0881,  2.2594],
         [-0.7206, -3.0489,  0.8148, -1.1983,  0.4801],
         [-1.1846,  1.5373, -4.2876,  0.6802,  0.2505]],

        [[-1.0028, -4.4051, -0.5975,  0.4702,  0.3740],
         [ 1.3914,  0.6693, -3.0174, -2.8063, -1.4639],
         [ 0.0989,  2.7267, -0.9380,  0.6380,  0.5891],
         [-0.0998, -8.8059, -1.4739, -3.5170, -1.2367]]])

In [8]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
mul = a.matmul(a.T)
mul, mul.shape

(tensor([[15.3495, -9.4476,  2.5918, -4.3929, -4.5805, -3.8545],
         [-9.4476,  9.0502, -3.9884,  1.8358,  6.5275,  4.5734],
         [ 2.5918, -3.9884, 13.6861, -2.1333, -5.3526, -4.1323],
         [-4.3929,  1.8358, -2.1333,  8.1810,  2.2857, -0.7460],
         [-4.5805,  6.5275, -5.3526,  2.2857, 10.8548,  4.4681],
         [-3.8545,  4.5734, -4.1323, -0.7460,  4.4681, 11.1646]]),
 torch.Size([6, 6]))

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

# руками по x: 3x**2 = 3 * 1 ** 2 = 3 * 1 = 3

In [10]:
x = torch.FloatTensor([1])
x 

tensor([1.])

In [11]:
x.requires_grad_()

tensor([1.], requires_grad=True)

In [12]:
z = torch.tensor(0.5)
t = torch.tensor(2)

In [13]:
y = x**3 + z - 75 * t

In [14]:
y

tensor([-148.5000], grad_fn=<SubBackward0>)

In [15]:
x.grad

In [16]:
y.backward(x)

In [17]:
x.grad

tensor([3.])

In [18]:
# Создайте единичный тензор размера 5x6
e = torch.ones(5, 6)
e

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [21]:
# Переведите его в формат numpy
e.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)